[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.0"

[[override]]
  name = "k8s.io/client-go"
  version = "=0.16.6"

[[override]]
  name = "k8s.io/klog"
  version = "v1.0.0"


