// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/v1/container_orchestrator.proto

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// KVGetRequest contains the keys to retrieve from the KV store
type KVGetRequest struct {
	// List of keys to retrieve (e.g., ["arcus/v3/certdata"])
	Key []string `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
}

func (m *KVGetRequest) Reset()         { *m = KVGetRequest{} }
func (m *KVGetRequest) String() string { return proto.CompactTextString(m) }
func (*KVGetRequest) ProtoMessage()    {}
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{0}
}
func (m *KVGetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVGetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVGetRequest.Merge(m, src)
}
func (m *KVGetRequest) XXX_Size() int {
	return m.Size()
}
func (m *KVGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVGetRequest proto.InternalMessageInfo

func (m *KVGetRequest) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

// ValuePair represents a key-value pair
type ValuePair struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *ValuePair) Reset()         { *m = ValuePair{} }
func (m *ValuePair) String() string { return proto.CompactTextString(m) }
func (*ValuePair) ProtoMessage()    {}
func (*ValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{1}
}
func (m *ValuePair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValuePair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuePair.Merge(m, src)
}
func (m *ValuePair) XXX_Size() int {
	return m.Size()
}
func (m *ValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_ValuePair proto.InternalMessageInfo

func (m *ValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// KVGetResponse contains the retrieved key-value pairs
type KVGetResponse struct {
	// List of key-value pairs
	Pair []*ValuePair `protobuf:"bytes,1,rep,name=pair,proto3" json:"pair,omitempty"`
}

func (m *KVGetResponse) Reset()         { *m = KVGetResponse{} }
func (m *KVGetResponse) String() string { return proto.CompactTextString(m) }
func (*KVGetResponse) ProtoMessage()    {}
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{2}
}
func (m *KVGetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVGetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVGetResponse.Merge(m, src)
}
func (m *KVGetResponse) XXX_Size() int {
	return m.Size()
}
func (m *KVGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KVGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KVGetResponse proto.InternalMessageInfo

func (m *KVGetResponse) GetPair() []*ValuePair {
	if m != nil {
		return m.Pair
	}
	return nil
}

// KVSetRequest contains the key-value pair to store
type KVSetRequest struct {
	// Key name (e.g., "arcus/v3/certdata")
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// JSON-encoded certificate data
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *KVSetRequest) Reset()         { *m = KVSetRequest{} }
func (m *KVSetRequest) String() string { return proto.CompactTextString(m) }
func (*KVSetRequest) ProtoMessage()    {}
func (*KVSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{3}
}
func (m *KVSetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVSetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSetRequest.Merge(m, src)
}
func (m *KVSetRequest) XXX_Size() int {
	return m.Size()
}
func (m *KVSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVSetRequest proto.InternalMessageInfo

func (m *KVSetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVSetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// KVSetResponse is returned after successfully storing data
type KVSetResponse struct {
}

func (m *KVSetResponse) Reset()         { *m = KVSetResponse{} }
func (m *KVSetResponse) String() string { return proto.CompactTextString(m) }
func (*KVSetResponse) ProtoMessage()    {}
func (*KVSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{4}
}
func (m *KVSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSetResponse.Merge(m, src)
}
func (m *KVSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *KVSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KVSetResponse proto.InternalMessageInfo

// KVDeleteRequest contains the key to delete
type KVDeleteRequest struct {
	// Key name to delete
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *KVDeleteRequest) Reset()         { *m = KVDeleteRequest{} }
func (m *KVDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*KVDeleteRequest) ProtoMessage()    {}
func (*KVDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{5}
}
func (m *KVDeleteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVDeleteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVDeleteRequest.Merge(m, src)
}
func (m *KVDeleteRequest) XXX_Size() int {
	return m.Size()
}
func (m *KVDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVDeleteRequest proto.InternalMessageInfo

func (m *KVDeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// KVDeleteResponse is returned after successfully deleting data
type KVDeleteResponse struct {
}

func (m *KVDeleteResponse) Reset()         { *m = KVDeleteResponse{} }
func (m *KVDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*KVDeleteResponse) ProtoMessage()    {}
func (*KVDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{6}
}
func (m *KVDeleteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KVDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KVDeleteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KVDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVDeleteResponse.Merge(m, src)
}
func (m *KVDeleteResponse) XXX_Size() int {
	return m.Size()
}
func (m *KVDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KVDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KVDeleteResponse proto.InternalMessageInfo

// GetBearerTokenRequest is used to request a bearer token
type GetBearerTokenRequest struct {
	// Refresh token for authentication
	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Token expiration (e.g., "1m" for 1 minute, "1h" for 1 hour, "1d" for 1 day)
	// Maximum is 1d, minimum is 1s. Invalid or empty exp will resolve to 1d
	Exp string `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (m *GetBearerTokenRequest) Reset()         { *m = GetBearerTokenRequest{} }
func (m *GetBearerTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetBearerTokenRequest) ProtoMessage()    {}
func (*GetBearerTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{7}
}
func (m *GetBearerTokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBearerTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBearerTokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBearerTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBearerTokenRequest.Merge(m, src)
}
func (m *GetBearerTokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetBearerTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBearerTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBearerTokenRequest proto.InternalMessageInfo

func (m *GetBearerTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetBearerTokenRequest) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

// GetBearerTokenResponse contains the bearer token
type GetBearerTokenResponse struct {
	// Bearer token for authentication
	BearerToken string `protobuf:"bytes,1,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
}

func (m *GetBearerTokenResponse) Reset()         { *m = GetBearerTokenResponse{} }
func (m *GetBearerTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetBearerTokenResponse) ProtoMessage()    {}
func (*GetBearerTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{8}
}
func (m *GetBearerTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBearerTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBearerTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetBearerTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBearerTokenResponse.Merge(m, src)
}
func (m *GetBearerTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetBearerTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBearerTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBearerTokenResponse proto.InternalMessageInfo

func (m *GetBearerTokenResponse) GetBearerToken() string {
	if m != nil {
		return m.BearerToken
	}
	return ""
}

type GetCustomerProxySettingsRequest struct {
}

func (m *GetCustomerProxySettingsRequest) Reset()         { *m = GetCustomerProxySettingsRequest{} }
func (m *GetCustomerProxySettingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerProxySettingsRequest) ProtoMessage()    {}
func (*GetCustomerProxySettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{9}
}
func (m *GetCustomerProxySettingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetCustomerProxySettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetCustomerProxySettingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetCustomerProxySettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerProxySettingsRequest.Merge(m, src)
}
func (m *GetCustomerProxySettingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetCustomerProxySettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerProxySettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerProxySettingsRequest proto.InternalMessageInfo

type GetCustomerProxySettingsResponse struct {
	// Types that are valid to be assigned to Content:
	//	*GetCustomerProxySettingsResponse_CustomerProxySettings
	//	*GetCustomerProxySettingsResponse_Empty
	Content isGetCustomerProxySettingsResponse_Content `protobuf_oneof:"content"`
}

func (m *GetCustomerProxySettingsResponse) Reset()         { *m = GetCustomerProxySettingsResponse{} }
func (m *GetCustomerProxySettingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerProxySettingsResponse) ProtoMessage()    {}
func (*GetCustomerProxySettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{10}
}
func (m *GetCustomerProxySettingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetCustomerProxySettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetCustomerProxySettingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetCustomerProxySettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerProxySettingsResponse.Merge(m, src)
}
func (m *GetCustomerProxySettingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetCustomerProxySettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerProxySettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerProxySettingsResponse proto.InternalMessageInfo

type isGetCustomerProxySettingsResponse_Content interface {
	isGetCustomerProxySettingsResponse_Content()
	MarshalTo([]byte) (int, error)
	Size() int
}

type GetCustomerProxySettingsResponse_CustomerProxySettings struct {
	CustomerProxySettings *CustomerProxySettings `protobuf:"bytes,1,opt,name=customer_proxy_settings,json=customerProxySettings,proto3,oneof" json:"customer_proxy_settings,omitempty"`
}
type GetCustomerProxySettingsResponse_Empty struct {
	Empty *types.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof" json:"empty,omitempty"`
}

func (*GetCustomerProxySettingsResponse_CustomerProxySettings) isGetCustomerProxySettingsResponse_Content() {
}
func (*GetCustomerProxySettingsResponse_Empty) isGetCustomerProxySettingsResponse_Content() {}

func (m *GetCustomerProxySettingsResponse) GetContent() isGetCustomerProxySettingsResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GetCustomerProxySettingsResponse) GetCustomerProxySettings() *CustomerProxySettings {
	if x, ok := m.GetContent().(*GetCustomerProxySettingsResponse_CustomerProxySettings); ok {
		return x.CustomerProxySettings
	}
	return nil
}

func (m *GetCustomerProxySettingsResponse) GetEmpty() *types.Empty {
	if x, ok := m.GetContent().(*GetCustomerProxySettingsResponse_Empty); ok {
		return x.Empty
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCustomerProxySettingsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCustomerProxySettingsResponse_CustomerProxySettings)(nil),
		(*GetCustomerProxySettingsResponse_Empty)(nil),
	}
}

type CustomerProxySettings struct {
	// The hostname of the customer proxy
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The port of the customer proxy
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Base64 encoded username:password, which will be appended to the Authorization header
	Auth string `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// The protocol of the customer proxy. http or https
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (m *CustomerProxySettings) Reset()         { *m = CustomerProxySettings{} }
func (m *CustomerProxySettings) String() string { return proto.CompactTextString(m) }
func (*CustomerProxySettings) ProtoMessage()    {}
func (*CustomerProxySettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e617317b2838d9, []int{11}
}
func (m *CustomerProxySettings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustomerProxySettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustomerProxySettings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustomerProxySettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerProxySettings.Merge(m, src)
}
func (m *CustomerProxySettings) XXX_Size() int {
	return m.Size()
}
func (m *CustomerProxySettings) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerProxySettings.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerProxySettings proto.InternalMessageInfo

func (m *CustomerProxySettings) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CustomerProxySettings) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CustomerProxySettings) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *CustomerProxySettings) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func init() {
	proto.RegisterType((*KVGetRequest)(nil), "com.purestorage.ems.KVGetRequest")
	proto.RegisterType((*ValuePair)(nil), "com.purestorage.ems.ValuePair")
	proto.RegisterType((*KVGetResponse)(nil), "com.purestorage.ems.KVGetResponse")
	proto.RegisterType((*KVSetRequest)(nil), "com.purestorage.ems.KVSetRequest")
	proto.RegisterType((*KVSetResponse)(nil), "com.purestorage.ems.KVSetResponse")
	proto.RegisterType((*KVDeleteRequest)(nil), "com.purestorage.ems.KVDeleteRequest")
	proto.RegisterType((*KVDeleteResponse)(nil), "com.purestorage.ems.KVDeleteResponse")
	proto.RegisterType((*GetBearerTokenRequest)(nil), "com.purestorage.ems.GetBearerTokenRequest")
	proto.RegisterType((*GetBearerTokenResponse)(nil), "com.purestorage.ems.GetBearerTokenResponse")
	proto.RegisterType((*GetCustomerProxySettingsRequest)(nil), "com.purestorage.ems.GetCustomerProxySettingsRequest")
	proto.RegisterType((*GetCustomerProxySettingsResponse)(nil), "com.purestorage.ems.GetCustomerProxySettingsResponse")
	proto.RegisterType((*CustomerProxySettings)(nil), "com.purestorage.ems.CustomerProxySettings")
}

func init() {
	proto.RegisterFile("pkg/apis/v1/container_orchestrator.proto", fileDescriptor_f0e617317b2838d9)
}

var fileDescriptor_f0e617317b2838d9 = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x4f, 0x13, 0x4f,
	0x14, 0xee, 0xd2, 0xf6, 0xf7, 0x83, 0x29, 0x08, 0x19, 0x29, 0x36, 0xab, 0x2e, 0x30, 0x60, 0x24,
	0x35, 0x6c, 0x63, 0x51, 0x0f, 0x78, 0x03, 0x0d, 0x18, 0x12, 0x6d, 0x5a, 0xc3, 0xc1, 0x4b, 0x33,
	0x2d, 0xaf, 0xdb, 0x4d, 0xdb, 0x9d, 0x75, 0x66, 0x5a, 0xc1, 0xa3, 0x07, 0xbd, 0x9a, 0x78, 0x37,
	0xfe, 0x1b, 0x9e, 0xbd, 0x78, 0x24, 0xf1, 0xe2, 0xd1, 0x80, 0x7f, 0x88, 0x99, 0xd9, 0x29, 0xa5,
	0x66, 0xdb, 0xca, 0x6d, 0xe6, 0xbd, 0xef, 0x7d, 0xdf, 0xb7, 0xb3, 0xef, 0x43, 0x1b, 0x61, 0xcb,
	0x2b, 0xd0, 0xd0, 0x17, 0x85, 0xde, 0xfd, 0x42, 0x9d, 0x05, 0x92, 0xfa, 0x01, 0xf0, 0x2a, 0xe3,
	0xf5, 0x26, 0x08, 0xc9, 0xa9, 0x64, 0xdc, 0x0d, 0x39, 0x93, 0x0c, 0x5f, 0xaf, 0xb3, 0x8e, 0x1b,
	0x76, 0x39, 0x08, 0xc9, 0x38, 0xf5, 0xc0, 0x85, 0x8e, 0xb0, 0x6f, 0x79, 0x8c, 0x79, 0x6d, 0x50,
	0x0c, 0x05, 0x1a, 0x04, 0x4c, 0x52, 0xe9, 0xb3, 0x40, 0x44, 0x23, 0xf6, 0x4d, 0xd3, 0xd5, 0xb7,
	0x5a, 0xb7, 0x51, 0x80, 0x4e, 0x28, 0x4f, 0xa2, 0x26, 0x59, 0x41, 0xb3, 0x07, 0x87, 0x7b, 0x20,
	0xcb, 0xf0, 0xba, 0x0b, 0x42, 0xe2, 0x05, 0x94, 0x6c, 0xc1, 0x49, 0xce, 0x5a, 0x49, 0x6e, 0xcc,
	0x94, 0xd5, 0x91, 0x6c, 0xa1, 0x99, 0x43, 0xda, 0xee, 0x42, 0x89, 0xfa, 0x7c, 0xd0, 0xb6, 0x4c,
	0x1b, 0x2f, 0xa2, 0x74, 0x4f, 0xb5, 0x73, 0x53, 0xba, 0x16, 0x5d, 0xc8, 0x2e, 0x9a, 0x33, 0xb4,
	0x22, 0x64, 0x81, 0x00, 0x5c, 0x44, 0xa9, 0x90, 0xfa, 0x5c, 0x13, 0x67, 0x8a, 0x8e, 0x1b, 0xf3,
	0x19, 0xee, 0x85, 0x4c, 0x59, 0x63, 0xc9, 0x23, 0xe5, 0xad, 0x12, 0xe3, 0x6d, 0x82, 0xf8, 0xbc,
	0x12, 0xaf, 0x0c, 0xc4, 0xc9, 0x1a, 0x9a, 0x3f, 0x38, 0x7c, 0x02, 0x6d, 0x90, 0x30, 0x92, 0x8b,
	0x60, 0xb4, 0x30, 0x00, 0x99, 0xc1, 0xe7, 0x28, 0xbb, 0x07, 0x72, 0x07, 0x28, 0x07, 0xfe, 0x92,
	0xb5, 0x20, 0xe8, 0x8f, 0xaf, 0xa1, 0x39, 0x0e, 0x0d, 0x0e, 0xa2, 0x59, 0x95, 0xaa, 0x6e, 0x88,
	0x66, 0x4d, 0x51, 0x63, 0x95, 0x06, 0x1c, 0x87, 0xc6, 0x9b, 0x3a, 0x92, 0xc7, 0x68, 0xe9, 0x6f,
	0x3e, 0xf3, 0x3e, 0xab, 0x68, 0xb6, 0xa6, 0xcb, 0x43, 0x7c, 0x99, 0xda, 0x00, 0x4a, 0x56, 0xd1,
	0xf2, 0x1e, 0xc8, 0xdd, 0xae, 0x90, 0xac, 0x03, 0xbc, 0xc4, 0xd9, 0xf1, 0x49, 0x05, 0xa4, 0xf4,
	0x03, 0x4f, 0x18, 0x5b, 0xe4, 0x9b, 0x85, 0x56, 0x46, 0x63, 0x8c, 0xd4, 0x11, 0xba, 0x51, 0x37,
	0x80, 0x6a, 0xa8, 0x10, 0x55, 0x61, 0x20, 0x5a, 0x35, 0x53, 0xcc, 0xc7, 0xfe, 0x9d, 0x58, 0xd2,
	0xfd, 0x44, 0x39, 0x5b, 0x8f, 0x6b, 0x60, 0x17, 0xa5, 0xf5, 0x9e, 0xe9, 0xcf, 0xcf, 0x14, 0x97,
	0xdc, 0x68, 0x0b, 0xdd, 0xfe, 0x16, 0xba, 0x4f, 0x55, 0x77, 0x3f, 0x51, 0x8e, 0x60, 0x3b, 0x33,
	0xe8, 0x7f, 0xb5, 0xf8, 0x10, 0x48, 0xf2, 0x06, 0x65, 0x63, 0xc5, 0xb0, 0x8d, 0xa6, 0x9b, 0x4c,
	0xc8, 0x80, 0x76, 0xc0, 0x3c, 0xd0, 0xc5, 0x1d, 0x63, 0x94, 0x0a, 0x19, 0x97, 0x5a, 0x2e, 0x5d,
	0xd6, 0x67, 0x55, 0xa3, 0x5d, 0xd9, 0xcc, 0x25, 0x35, 0x56, 0x9f, 0x15, 0x87, 0xb6, 0x50, 0x67,
	0xed, 0x5c, 0x2a, 0xe2, 0xe8, 0xdf, 0x8b, 0x5f, 0x53, 0x28, 0xbb, 0xdb, 0x4f, 0xdf, 0x8b, 0x4b,
	0xe1, 0xc3, 0x6f, 0x51, 0x5a, 0xef, 0x33, 0x5e, 0x8d, 0x7d, 0x9b, 0xcb, 0x11, 0xb2, 0xc9, 0x38,
	0x88, 0x59, 0xac, 0xfc, 0xbb, 0x1f, 0xbf, 0x3f, 0x4d, 0xad, 0x93, 0xe5, 0xa1, 0xc0, 0x5f, 0xce,
	0x7b, 0xa1, 0xd5, 0xf3, 0x40, 0x6e, 0x5b, 0xf9, 0x48, 0xbb, 0x32, 0x46, 0xbb, 0x32, 0x59, 0xbb,
	0x72, 0x55, 0x6d, 0x11, 0x69, 0xbf, 0xb7, 0xd0, 0x74, 0x3f, 0x15, 0x78, 0x7d, 0x04, 0xf9, 0x50,
	0xb2, 0xec, 0x3b, 0x13, 0x50, 0xc6, 0xc5, 0xa6, 0x76, 0x71, 0x97, 0x90, 0x71, 0x2e, 0x8e, 0xf4,
	0x8c, 0x32, 0xf2, 0xd9, 0x42, 0xd7, 0x86, 0xa3, 0x83, 0xe3, 0xd7, 0x34, 0x36, 0xaf, 0xf6, 0xbd,
	0x7f, 0xc2, 0x1a, 0x6b, 0x5b, 0xda, 0xda, 0x26, 0xd9, 0x18, 0x6d, 0xcd, 0x03, 0x19, 0x45, 0x53,
	0xa7, 0x75, 0xdb, 0xca, 0x17, 0xbf, 0x58, 0x68, 0xb1, 0xd4, 0xa6, 0xb2, 0xc1, 0x78, 0xe7, 0x59,
	0xd0, 0x60, 0x25, 0xce, 0x7a, 0xfe, 0x11, 0x70, 0xfc, 0xc1, 0x42, 0xb9, 0x51, 0x99, 0xc4, 0x0f,
	0x46, 0xf9, 0x1a, 0x17, 0x73, 0xfb, 0xe1, 0x15, 0xa7, 0xa2, 0xef, 0xda, 0xb9, 0xfd, 0xfd, 0xcc,
	0xb1, 0x4e, 0xcf, 0x1c, 0xeb, 0xd7, 0x99, 0x63, 0x7d, 0x3c, 0x77, 0x12, 0xa7, 0xe7, 0x4e, 0xe2,
	0xe7, 0xb9, 0x93, 0x78, 0x95, 0xa4, 0xa1, 0x5f, 0xfb, 0x4f, 0xe7, 0x60, 0xeb, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x88, 0x50, 0x15, 0xfc, 0x8d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContainerOrchestratorClient is the client API for ContainerOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContainerOrchestratorClient interface {
	// Get certificate data from Kubernetes Secret
	KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error)
	// Store certificate data in Kubernetes Secret
	KVSet(ctx context.Context, in *KVSetRequest, opts ...grpc.CallOption) (*KVSetResponse, error)
	// Delete certificate data from Kubernetes Secret
	KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error)
	// Get bearer token for authentication (required by CCM-Go)
	GetBearerToken(ctx context.Context, in *GetBearerTokenRequest, opts ...grpc.CallOption) (*GetBearerTokenResponse, error)
}

type containerOrchestratorClient struct {
	cc *grpc.ClientConn
}

func NewContainerOrchestratorClient(cc *grpc.ClientConn) ContainerOrchestratorClient {
	return &containerOrchestratorClient{cc}
}

func (c *containerOrchestratorClient) KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error) {
	out := new(KVGetResponse)
	err := c.cc.Invoke(ctx, "/com.purestorage.ems.ContainerOrchestrator/KVGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerOrchestratorClient) KVSet(ctx context.Context, in *KVSetRequest, opts ...grpc.CallOption) (*KVSetResponse, error) {
	out := new(KVSetResponse)
	err := c.cc.Invoke(ctx, "/com.purestorage.ems.ContainerOrchestrator/KVSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerOrchestratorClient) KVDelete(ctx context.Context, in *KVDeleteRequest, opts ...grpc.CallOption) (*KVDeleteResponse, error) {
	out := new(KVDeleteResponse)
	err := c.cc.Invoke(ctx, "/com.purestorage.ems.ContainerOrchestrator/KVDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerOrchestratorClient) GetBearerToken(ctx context.Context, in *GetBearerTokenRequest, opts ...grpc.CallOption) (*GetBearerTokenResponse, error) {
	out := new(GetBearerTokenResponse)
	err := c.cc.Invoke(ctx, "/com.purestorage.ems.ContainerOrchestrator/GetBearerToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerOrchestratorServer is the server API for ContainerOrchestrator service.
type ContainerOrchestratorServer interface {
	// Get certificate data from Kubernetes Secret
	KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error)
	// Store certificate data in Kubernetes Secret
	KVSet(context.Context, *KVSetRequest) (*KVSetResponse, error)
	// Delete certificate data from Kubernetes Secret
	KVDelete(context.Context, *KVDeleteRequest) (*KVDeleteResponse, error)
	// Get bearer token for authentication (required by CCM-Go)
	GetBearerToken(context.Context, *GetBearerTokenRequest) (*GetBearerTokenResponse, error)
}

// UnimplementedContainerOrchestratorServer can be embedded to have forward compatible implementations.
type UnimplementedContainerOrchestratorServer struct {
}

func (*UnimplementedContainerOrchestratorServer) KVGet(ctx context.Context, req *KVGetRequest) (*KVGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVGet not implemented")
}
func (*UnimplementedContainerOrchestratorServer) KVSet(ctx context.Context, req *KVSetRequest) (*KVSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVSet not implemented")
}
func (*UnimplementedContainerOrchestratorServer) KVDelete(ctx context.Context, req *KVDeleteRequest) (*KVDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVDelete not implemented")
}
func (*UnimplementedContainerOrchestratorServer) GetBearerToken(ctx context.Context, req *GetBearerTokenRequest) (*GetBearerTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBearerToken not implemented")
}

func RegisterContainerOrchestratorServer(s *grpc.Server, srv ContainerOrchestratorServer) {
	s.RegisterService(&_ContainerOrchestrator_serviceDesc, srv)
}

func _ContainerOrchestrator_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerOrchestratorServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.purestorage.ems.ContainerOrchestrator/KVGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerOrchestratorServer).KVGet(ctx, req.(*KVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerOrchestrator_KVSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerOrchestratorServer).KVSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.purestorage.ems.ContainerOrchestrator/KVSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerOrchestratorServer).KVSet(ctx, req.(*KVSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerOrchestrator_KVDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerOrchestratorServer).KVDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.purestorage.ems.ContainerOrchestrator/KVDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerOrchestratorServer).KVDelete(ctx, req.(*KVDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerOrchestrator_GetBearerToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBearerTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerOrchestratorServer).GetBearerToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.purestorage.ems.ContainerOrchestrator/GetBearerToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerOrchestratorServer).GetBearerToken(ctx, req.(*GetBearerTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerOrchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.purestorage.ems.ContainerOrchestrator",
	HandlerType: (*ContainerOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KVGet",
			Handler:    _ContainerOrchestrator_KVGet_Handler,
		},
		{
			MethodName: "KVSet",
			Handler:    _ContainerOrchestrator_KVSet_Handler,
		},
		{
			MethodName: "KVDelete",
			Handler:    _ContainerOrchestrator_KVDelete_Handler,
		},
		{
			MethodName: "GetBearerToken",
			Handler:    _ContainerOrchestrator_GetBearerToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/v1/container_orchestrator.proto",
}

// PlatformInfoProviderClient is the client API for PlatformInfoProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformInfoProviderClient interface {
	// Returns the customer proxy settings, such as hostname, port, and auth string.
	// In case the customer proxy is not configured, the response will be of type Empty.
	GetCustomerProxySettings(ctx context.Context, in *GetCustomerProxySettingsRequest, opts ...grpc.CallOption) (*GetCustomerProxySettingsResponse, error)
}

type platformInfoProviderClient struct {
	cc *grpc.ClientConn
}

func NewPlatformInfoProviderClient(cc *grpc.ClientConn) PlatformInfoProviderClient {
	return &platformInfoProviderClient{cc}
}

func (c *platformInfoProviderClient) GetCustomerProxySettings(ctx context.Context, in *GetCustomerProxySettingsRequest, opts ...grpc.CallOption) (*GetCustomerProxySettingsResponse, error) {
	out := new(GetCustomerProxySettingsResponse)
	err := c.cc.Invoke(ctx, "/com.purestorage.ems.PlatformInfoProvider/GetCustomerProxySettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformInfoProviderServer is the server API for PlatformInfoProvider service.
type PlatformInfoProviderServer interface {
	// Returns the customer proxy settings, such as hostname, port, and auth string.
	// In case the customer proxy is not configured, the response will be of type Empty.
	GetCustomerProxySettings(context.Context, *GetCustomerProxySettingsRequest) (*GetCustomerProxySettingsResponse, error)
}

// UnimplementedPlatformInfoProviderServer can be embedded to have forward compatible implementations.
type UnimplementedPlatformInfoProviderServer struct {
}

func (*UnimplementedPlatformInfoProviderServer) GetCustomerProxySettings(ctx context.Context, req *GetCustomerProxySettingsRequest) (*GetCustomerProxySettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerProxySettings not implemented")
}

func RegisterPlatformInfoProviderServer(s *grpc.Server, srv PlatformInfoProviderServer) {
	s.RegisterService(&_PlatformInfoProvider_serviceDesc, srv)
}

func _PlatformInfoProvider_GetCustomerProxySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerProxySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformInfoProviderServer).GetCustomerProxySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.purestorage.ems.PlatformInfoProvider/GetCustomerProxySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformInfoProviderServer).GetCustomerProxySettings(ctx, req.(*GetCustomerProxySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlatformInfoProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.purestorage.ems.PlatformInfoProvider",
	HandlerType: (*PlatformInfoProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerProxySettings",
			Handler:    _PlatformInfoProvider_GetCustomerProxySettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/v1/container_orchestrator.proto",
}

func (m *KVGetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVGetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVGetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		for iNdEx := len(m.Key) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Key[iNdEx])
			copy(dAtA[i:], m.Key[iNdEx])
			i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Key[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValuePair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValuePair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValuePair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KVGetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVGetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVGetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Pair) > 0 {
		for iNdEx := len(m.Pair) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pair[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintContainerOrchestrator(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *KVSetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVSetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVSetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KVSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *KVDeleteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVDeleteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVDeleteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KVDeleteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KVDeleteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KVDeleteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetBearerTokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBearerTokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBearerTokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Exp) > 0 {
		i -= len(m.Exp)
		copy(dAtA[i:], m.Exp)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Exp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RefreshToken) > 0 {
		i -= len(m.RefreshToken)
		copy(dAtA[i:], m.RefreshToken)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.RefreshToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetBearerTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBearerTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetBearerTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BearerToken) > 0 {
		i -= len(m.BearerToken)
		copy(dAtA[i:], m.BearerToken)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.BearerToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetCustomerProxySettingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetCustomerProxySettingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCustomerProxySettingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetCustomerProxySettingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetCustomerProxySettingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCustomerProxySettingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Content != nil {
		{
			size := m.Content.Size()
			i -= size
			if _, err := m.Content.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetCustomerProxySettingsResponse_CustomerProxySettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCustomerProxySettingsResponse_CustomerProxySettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomerProxySettings != nil {
		{
			size, err := m.CustomerProxySettings.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintContainerOrchestrator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *GetCustomerProxySettingsResponse_Empty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetCustomerProxySettingsResponse_Empty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Empty != nil {
		{
			size, err := m.Empty.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintContainerOrchestrator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *CustomerProxySettings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustomerProxySettings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomerProxySettings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Protocol) > 0 {
		i -= len(m.Protocol)
		copy(dAtA[i:], m.Protocol)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Protocol)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Auth) > 0 {
		i -= len(m.Auth)
		copy(dAtA[i:], m.Auth)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Auth)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Port != 0 {
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Hostname) > 0 {
		i -= len(m.Hostname)
		copy(dAtA[i:], m.Hostname)
		i = encodeVarintContainerOrchestrator(dAtA, i, uint64(len(m.Hostname)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContainerOrchestrator(dAtA []byte, offset int, v uint64) int {
	offset -= sovContainerOrchestrator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KVGetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Key) > 0 {
		for _, s := range m.Key {
			l = len(s)
			n += 1 + l + sovContainerOrchestrator(uint64(l))
		}
	}
	return n
}

func (m *ValuePair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func (m *KVGetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pair) > 0 {
		for _, e := range m.Pair {
			l = e.Size()
			n += 1 + l + sovContainerOrchestrator(uint64(l))
		}
	}
	return n
}

func (m *KVSetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func (m *KVSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *KVDeleteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func (m *KVDeleteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetBearerTokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RefreshToken)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	l = len(m.Exp)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func (m *GetBearerTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BearerToken)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func (m *GetCustomerProxySettingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetCustomerProxySettingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Content != nil {
		n += m.Content.Size()
	}
	return n
}

func (m *GetCustomerProxySettingsResponse_CustomerProxySettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomerProxySettings != nil {
		l = m.CustomerProxySettings.Size()
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}
func (m *GetCustomerProxySettingsResponse_Empty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Empty != nil {
		l = m.Empty.Size()
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}
func (m *CustomerProxySettings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovContainerOrchestrator(uint64(m.Port))
	}
	l = len(m.Auth)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	l = len(m.Protocol)
	if l > 0 {
		n += 1 + l + sovContainerOrchestrator(uint64(l))
	}
	return n
}

func sovContainerOrchestrator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContainerOrchestrator(x uint64) (n int) {
	return sovContainerOrchestrator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KVGetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVGetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVGetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValuePair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValuePair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValuePair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVGetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVGetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVGetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = append(m.Pair, &ValuePair{})
			if err := m.Pair[len(m.Pair)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVSetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVSetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVSetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVDeleteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVDeleteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVDeleteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KVDeleteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KVDeleteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KVDeleteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBearerTokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBearerTokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBearerTokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefreshToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefreshToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBearerTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBearerTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBearerTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearerToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BearerToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetCustomerProxySettingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetCustomerProxySettingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetCustomerProxySettingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetCustomerProxySettingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetCustomerProxySettingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetCustomerProxySettingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomerProxySettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CustomerProxySettings{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Content = &GetCustomerProxySettingsResponse_CustomerProxySettings{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Empty", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.Empty{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Content = &GetCustomerProxySettingsResponse_Empty{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CustomerProxySettings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustomerProxySettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustomerProxySettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auth = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Protocol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContainerOrchestrator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContainerOrchestrator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContainerOrchestrator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContainerOrchestrator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContainerOrchestrator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContainerOrchestrator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContainerOrchestrator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContainerOrchestrator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContainerOrchestrator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContainerOrchestrator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContainerOrchestrator = fmt.Errorf("proto: unexpected end of group")
)
